package stationQualityData;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSEnvCityDataSoap", targetNamespace = "http://tempuri.org/")
public interface WSEnvCityDataSoap {

	/**
	 * 
	 * @param pwd
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "StationQualityData", action = "http://tempuri.org/StationQualityData")
	@WebResult(name = "StationQualityDataResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "StationQualityData", targetNamespace = "http://tempuri.org/", className = "stationQualityData.StationQualityData")
	@ResponseWrapper(localName = "StationQualityDataResponse", targetNamespace = "http://tempuri.org/", className = "stationQualityData.StationQualityDataResponse")
	public String stationQualityData(
			@WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
			@WebParam(name = "pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param pwd
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CityLiveQualityData", action = "http://tempuri.org/CityLiveQualityData")
	@WebResult(name = "CityLiveQualityDataResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CityLiveQualityData", targetNamespace = "http://tempuri.org/", className = "stationQualityData.CityLiveQualityData")
	@ResponseWrapper(localName = "CityLiveQualityDataResponse", targetNamespace = "http://tempuri.org/", className = "stationQualityData.CityLiveQualityDataResponse")
	public String cityLiveQualityData(
			@WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
			@WebParam(name = "pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param pwd
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CityDayQualityData", action = "http://tempuri.org/CityDayQualityData")
	@WebResult(name = "CityDayQualityDataResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CityDayQualityData", targetNamespace = "http://tempuri.org/", className = "stationQualityData.CityDayQualityData")
	@ResponseWrapper(localName = "CityDayQualityDataResponse", targetNamespace = "http://tempuri.org/", className = "stationQualityData.CityDayQualityDataResponse")
	public String cityDayQualityData(
			@WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
			@WebParam(name = "pwd", targetNamespace = "http://tempuri.org/") String pwd);

}
